#!/usr/bin/env bash
# encswap - Set up encryption on a non-encrypted swap partition
# Usage: encswap [<swapdevice>]
# Required: mount(swapon swapoff) coreutils(ls head) grep sed wget apt patch

[[ $1 ]] && swapdev=$1 || swapdev=$(swapon --show=NAME --noheadings)
swapdev=${swapdev#/} swapdev=${swapdev#dev/}
swapid=$(ls -l /dev/disk/by-id |grep "/$swapdev$" |head -1 |cut -d' ' -f9)
[[ -z $swapid ]] && echo "No swap device mounted or given" && exit 1
id=/dev/disk/by-id/$swapid
sudo swapoff /dev/$swapdev || :

echo -e "\n=== Encrypting non-encrypted swap partition ===\n"

sudo apt install cryptsetup

# Patch systemd for Encrypted ZFS
patch=launchpadlibrarian.net/478315221/2150-fix-systemd-dependency-loops.patch
file1=/lib/systemd/system-generators/zfs-mount-generator
[[ -f $file1 ]] && ! grep -q 'zpool list -H -o name' "$file1" &&
	wget -qO- "https://$patch" |sed -e 's@/etc@/lib@' -e 's@\.in$@@' |
		(cd /; sudo patch -p1)

# Comment-out current swap line in /etc/fstab and append new one
sudo sed -i "/^\/dev\/$swapdev /s/^/#/g" /etc/fstab
sudo sed -i "/^${id//\//\\/} /s/^/#/g" /etc/fstab
add="/dev/mapper/swap encswap swap defaults 0 0"
grep -q "^$add" /etc/fstab ||
	echo "$add" |sudo tee -a /etc/fstab

# Append line to crypttab
add="swap $id /dev/urandom swap,cipher=aes-xts-plain64:sha256,size=512"
grep -q "^$add" /etc/crypttab ||
	echo "$add" |sudo tee -a /etc/crypttab

echo "Reboot recommended to start using encrypted swap"
