#!/usr/bin/env bash
set -e
# encswap - Set up encryption on a non-encrypted swap partition
# Usage: encswap [<swapdevice>]
# Required: mount(swapon swapoff) coreutils(ls head) grep sed wget apt patch

[[ $1 ]] && swapdev=$1 || swapdev=$(swapon --show=NAME --noheadings)
swapdev=${swapdev#/} swapdev=${swapdev#dev/}
swapid=$(ls -l /dev/disk/by-id |grep "/$swapdev$" |head -1 |cut -d' ' -f9)
[[ -z $swapid ]] && echo "No swap device mounted or given" && exit 1
id=/dev/disk/by-id/$swapid
sudo swapoff /dev/$swapdev || :

echo -e "\n=== Encrypting non-encrypted swap partition ===\n"

sudo apt install cryptsetup

# Patch systemd for Encrypted ZFS
patch=launchpadlibrarian.net/478315221/2150-fix-systemd-dependency-loops.patch
wget "https://$patch" |sed "s@/etc@/lib@; s@\.in$@@" |(cd /; sudo patch -p1)

# Comment-out current swap line in /etc/fstab and append new one
sudo sed -i "/^\/dev\/$swapdev /s/^/#/g" /etc/fstab
sudo sed -i "/^$id /s/^/#/g" /etc/fstab
add="/dev/mapper/swap encswap swap defaults 0 0"
echo "$add" |sudo tee -a /etc/fstab

# Append line to crypttab
add="swap $id /dev/urandom swap,cipher=aes-xts-plain64:sha256,size=512"
echo "$add" |sudo tee -a /etc/crypttab

echo "Reboot recommended to start using encrypted swap"
