#!/usr/bin/env bash
# modubi - Run a modified Ubiquity installer to use encrypted ZFS

modified=/usr/share/ubiquity/zsys-setup
[[ ! -f $modified ]] && echo "Ubiquity not present" && exit 1

echo -e "\n=== Modifying the Ubiquity installer to use Encrypted ZFS ===\n"
echo "Once the graphical installer lauches, pick 'Advanced options' in the"
echo -e " 'Installation' screen and then choose the 'ZFS' option.\n"
echo "The swap partition must also get encrypted on every boot!"
echo "This can be done after booting for the first time into the new system."
echo "The script at https://4e4.win/encswap can be used to do this:"
echo -e "\n  wget 4e4.win/encswap\n  bash encswap\n"

# Ask for the passphrase to be used
read -rp "New passphrase to be used to decrypt the drive [Ctrl-C aborts]: "

# Install the packages for Ubiquity to offer ZFS
echo "Installing the required packages for ZFS"
sudo apt install libzfs2linux zfs-initramfs zfsutils-linux zfs-zed

# Echo the password into the 'zpool create' command
add="\\\techo '$REPLY' |"
sudo sed -i "/# rpool$/a $add" "$modified"

# Add the options to use the password on stdin
add='\\t\t-O encryption=aes-256-gcm \\'
add+='\n\t\t-O keylocation=prompt \\'
add+='\n\t\t-O keyformat=passphrase \\'
sudo sed -i "/-O mountpoint=\/ -R /i $add" "$modified"

ubiquity &
