#!/usr/bin/env bash

# Set preferred size for the EFI System Partition
efisize=1536

file=/usr/share/ubiquity/zsys-setup pw=
[[ ! -f $file ]] && echo "Ubiquity installer not present" && exit 1

# Get passphrase
echo -e '\n===  Modifying Ubiquity installer to use natively encrypted ZFS ==='
echo -e '\n  To abort, enter an empty password or do Ctrl_C.\n'
while [[ -z $pw ]]
do
	pw=$(systemd-ask-password '  Choose ZFS Encryption password:')
	[[ -z $pw ]] && echo '  Aborted' && exit 2
	((${#pw}<8)) && echo -e "  Password must be at least 8 characters\n" &&
		pw= && continue
	pw2=$(systemd-ask-password '  Confirm the entered password:')
	[[ -z $pw2 ]] && echo '  Aborted' && exit 2
	[[ ! $pw = $pw2 ]] && pw= && echo -e '  Passwords not the same. Again:\n'
done

# For Linux Mint, pulls all required packages to enable ZFS
sudo apt-get install --yes zfs-initramfs

# If already modified, start afresh with the backup, backup otherwise
grep -q ' # rpool' "$file" &&
	sudo cp /root/zsys-setup "$file" ||
	sudo cp "$file" /root

# Each sed command only modifies unmodified lines
# Pipe the password into the rpool creation command
sudo sed -i "/[^ ]# rpool$/ s@# rpool@echo '$pw' | \0@" "$file"
# Add encryption options for rpool
sudo sed -i '/[^ ]-O/ s@-O sync=disabled @-O encryption=aes-256-gcm -O keylocation=prompt -O keyformat=passphrase \0@' "$file"
# Change EFI System Partition size
sudo sed -i "/[^1-9]512M,/ s@512M,@${efisize}M,@" "$file"
# Add swap zvol
sudo sed -i "/[^ ]# System dataset$/a zfs create rpool/swap -V 1G -b $(getconf PAGESIZE) -o logbias=throughput -o sync=always  -o primarycache=metadata -o secondarycache=none\nmkswap -f /dev/zvol/rpool/swap" "$file"
sudo sed -i "/[^ ]# System dataset$/ s@#@ #@"
sudo sed -i "s@grep -Ev [^>]*@echo '/dev/zvol/rpool/swap zswap swap discard 0 0' @" "$file"
sudo sed -i 's@SWAPDEVICE=.*@SWAPDEVICE="/dev/zvol/rpool/swap"@' "$file"

# Remove EFI System Partition(s)
parts=$(ls -Al /dev/disk/by-partuuid 2>/dev/null |grep -o '[a-z][a-z0-9]*$')
for part in $parts
do num=${part##*[a-z]} disk=${part%$num} dev=/dev/$disk$num
	esp=$(sudo sgdisk -i$num /dev/$disk |
		grep C12A7328-F81F-11D2-BA4B-00A0C93EC93B)
 	if [[ $esp ]]
	then
		echo -e "\n  OK to wipe EFI System Partition $dev?\n"
		echo "  (Ctrl_C to abort, enter 'n' to keep $dev, Enter to wipe)"
		read
		[[ ! ${REPLY:0:1} = [nN] ]] && echo "  Wiping $dev..." &&
			sudo wipefs -a "$dev" && sudo partprobe "/dev/$disk"
	fi
done

cat <<EOM

  The Ubiquity graphical installer will start next, go through its screens.
  In its "Installation type" screen choose: "Erase disk and install ..."
  and then click on "Advanced features" and select:
  "EXPERIMENTAL: Erase disk and use ZFS" and click "OK" and then click
  "Install Now". Follow the screens and the install will proceed.

  (Ctrl_C to abort, Enter to start the Ubiquity installer)
EOM
read

ubiquity gtk_ui
